# Generated by Django 4.2.14 on 2024-08-27 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PCOS', models.CharField(max_length=3)),
                ('Age', models.IntegerField()),
                ('Weight', models.FloatField()),
                ('Height', models.FloatField()),
                ('BMI', models.FloatField()),
                ('Blood_Group', models.CharField(max_length=10)),
                ('Pulse_rate', models.FloatField()),
                ('RR', models.FloatField()),
                ('Hb', models.FloatField()),
                ('Marriage_Status', models.IntegerField()),
                ('Pregnant', models.CharField(max_length=3)),
                ('No_of_abortions', models.IntegerField()),
                ('TSH', models.FloatField()),
                ('PRG', models.FloatField()),
                ('RBS', models.FloatField()),
                ('Weight_gain', models.CharField(max_length=3)),
                ('Hair_loss', models.CharField(max_length=3)),
                ('Fast_food', models.CharField(max_length=3)),
                ('Reg_Exercise', models.CharField(max_length=3)),
                ('BP_Systolic', models.IntegerField()),
                ('BP_Diastolic', models.IntegerField()),
                ('Follicle_No_L', models.IntegerField()),
                ('Follicle_No_R', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('label', models.CharField(default='data', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
